name: Update Homebrew Formula

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Calculate SHA256
        id: sha256
        run: |
          # Download the release assets and calculate SHA256
          VERSION=${GITHUB_REF#refs/tags/}
          
          # For macOS x86_64
          curl -L -o macos_x86_64.tar.gz "https://github.com/Phara0h/WaspsWithBazookas/releases/download/${VERSION}/waspswithbazookas-macos-x86_64.tar.gz"
          SHA256_MACOS_X86_64=$(sha256sum macos_x86_64.tar.gz | cut -d' ' -f1)
          echo "sha256_macos_x86_64=$SHA256_MACOS_X86_64" >> $GITHUB_OUTPUT
          
          # For macOS aarch64
          curl -L -o macos_aarch64.tar.gz "https://github.com/Phara0h/WaspsWithBazookas/releases/download/${VERSION}/waspswithbazookas-macos-aarch64.tar.gz"
          SHA256_MACOS_AARCH64=$(sha256sum macos_aarch64.tar.gz | cut -d' ' -f1)
          echo "sha256_macos_aarch64=$SHA256_MACOS_AARCH64" >> $GITHUB_OUTPUT
          
          # For Linux x86_64
          curl -L -o linux_x86_64.tar.gz "https://github.com/Phara0h/WaspsWithBazookas/releases/download/${VERSION}/waspswithbazookas-linux-x86_64.tar.gz"
          SHA256_LINUX_X86_64=$(sha256sum linux_x86_64.tar.gz | cut -d' ' -f1)
          echo "sha256_linux_x86_64=$SHA256_LINUX_X86_64" >> $GITHUB_OUTPUT
          
          # For Linux aarch64
          curl -L -o linux_aarch64.tar.gz "https://github.com/Phara0h/WaspsWithBazookas/releases/download/${VERSION}/waspswithbazookas-linux-aarch64.tar.gz"
          SHA256_LINUX_AARCH64=$(sha256sum linux_aarch64.tar.gz | cut -d' ' -f1)
          echo "sha256_linux_aarch64=$SHA256_LINUX_AARCH64" >> $GITHUB_OUTPUT
      
      - name: Update Homebrew Formula
        uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          formula-name: waspswithbazookas
          homebrew-tap: Phara0h/homebrew-waspswithbazookas
          download-url: https://github.com/Phara0h/WaspsWithBazookas/releases/download/${{ github.event.release.tag_name }}/waspswithbazookas-macos-x86_64.tar.gz
          sha256: ${{ steps.sha256.outputs.sha256_macos_x86_64 }}
          commit-message: "Update waspswithbazookas to ${{ github.event.release.tag_name }}"
        env:
          COMMITTER_TOKEN: ${{ secrets.GITHUB_TOKEN }} 